server:
  port: 9412
  tomcat:
    uri-encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS  

spring:
  application:
    name: es-client
  sleuth:
    sampler:
      probability: 1.0
    rxjava:
      schedulers:
        ignoredthreads: HystrixMetricPoller,^RxComputation.*$,^RxIoScheduler.*$ #忽略rxjava相关线程，防止产生无意义的span
      
  zipkin:
    sender:
      type: kafka
    service:
      name: es-client   
    kafka:
      topic: zipkin
  kafka:
    bootstrap-servers: 39.108.176.135:9092
 


      
eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka
      #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
      #http://134.224.249.33:1111/eureka/  正式库
      #http://134.224.249.33:1111/eureka/  测试库
      #http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 2  
    instance-info-replication-interval-seconds: 2      
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 15 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.neusoft: DEBUG     
    com.netflix: DEBUG                    #用于心跳检测输出的日志
          